<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simplejava" nsURI="http://www.example.org/simplejava" nsPrefix="simplejava">
  <eClassifiers xsi:type="ecore:EClass" name="JPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contienent" upperBound="-1"
        eType="#//JPackage" eOpposite="#//JPackage/contient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contient" eType="#//JPackage"
        eOpposite="#//JPackage/contienent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//JClass" containment="true" eOpposite="#//JClass/jpackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//JInterface" containment="true" eOpposite="#//JInterface/jpackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JClass" eSuperTypes="#//JType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodes" upperBound="-1"
        eType="#//JMethode" containment="true" eOpposite="#//JMethode/classe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filles" upperBound="-1"
        eType="#//JClass" eOpposite="#//JClass/mere"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mere" eType="#//JClass"
        eOpposite="#//JClass/filles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jpackage" lowerBound="1"
        eType="#//JPackage" eOpposite="#//JPackage/classes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributs" upperBound="-1"
        eType="#//JAttribut" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//JInterface" eOpposite="#//JInterface/classes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JInterface" eSuperTypes="#//JType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mere" eType="#//JInterface"
        eOpposite="#//JInterface/filles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filles" upperBound="-1"
        eType="#//JInterface" eOpposite="#//JInterface/mere"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jpackage" lowerBound="1"
        eType="#//JPackage" eOpposite="#//JPackage/interfaces"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodes" upperBound="-1"
        eType="#//JMethode" containment="true" eOpposite="#//JMethode/interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//JClass" eOpposite="#//JClass/interfaces"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JType" eSuperTypes="#//JNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="JAttribut" eSuperTypes="#//JVariable #//JType"/>
  <eClassifiers xsi:type="ecore:EClass" name="JParametre" eSuperTypes="#//JVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="JVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="JNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JMethode" eSuperTypes="#//JType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametres" upperBound="-1"
        eType="#//JParametre" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estappelle" upperBound="-1"
        eType="#//JMethode" eOpposite="#//JMethode/appelle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appelle" upperBound="-1"
        eType="#//JMethode" eOpposite="#//JMethode/estappelle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classe" eType="#//JClass"
        eOpposite="#//JClass/methodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" eType="#//JInterface"
        eOpposite="#//JInterface/methodes"/>
  </eClassifiers>
</ecore:EPackage>
